# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: tac-agent-framework-hosted-agents
services:
    tac-agent-framework:
        project: .
        host: azure.ai.agent
        language: python
        config:
            container:
                resources:
                    cpu: "0.5"
                    memory: 1Gi
